- src/AppWindow.vala
- src/library/LibraryWindow.vala
> correct undo button position in header bar

- src/library/LibraryWindow.vala
* Remove a method that is only used once
* Don't create variables that never get used again
* Organize
> LibraryWindow.vala: remove build settings method

- src/library/LibraryWindow.vala
- src/library/TopDisplay.vala
* Update copyright header
* Change `app_label` to `title_label`
* change set methods to properties
* Reduce variable scope where possible
* Add white space
* Rename vague `top_grid` to more descriptive `progress_grid`
* Remove unnecessary properties from `progress_grid`
* Organize
* Code style
> TopDisplay.vala: Clean up and code style

- src/Checkerboard/CheckerboardItem.vala
* Change set methods to properties
* Add brackets
> CheckerboardItem.vala: change set methods to properties

- data/org.pantheon.photos-viewer.desktop.in.in
> Removed all keywords from photos-viewer desktop file

- src/Checkerboard/CheckerboardItem.vala
- src/Thumbnail.vala
- src/ThumbnailCache.vala
- src/library/LibraryWindow.vala
> HiDPI thumbnail support

- src/config/ConfigurationInterfaces.vala
- src/config/GSettingsEngine.vala
- src/library/LibraryWindow.vala
This goes some way towards #18 
I'm going to chip away at removing the ~2000 lines of really repetitive code for setting and getting settings in GSettings and just replace it with native GLib.Settings stuff.
> Port sidebar settings to native GSettings

- schemas/org.pantheon.photos.gschema.xml
- src/MediaPage.vala
- src/camera/ImportPage.vala
- src/config/ConfigurationInterfaces.vala
- src/config/GSettingsEngine.vala
- src/events/EventsDirectoryPage.vala
Also removes three keys from the schema that aren't used anywhere.
> Port display properties to native GSettings

- schemas/org.pantheon.photos.gschema.xml
- src/AppWindow.vala
- src/config/ConfigurationInterfaces.vala
- src/config/GSettingsEngine.vala
- src/direct/DirectWindow.vala
- src/library/LibraryWindow.vala
Also remove a `sidebar-position` key that isn't used.
> Port window size settings to native GSettings

- schemas/org.pantheon.photos.gschema.xml
- src/config/ConfigurationInterfaces.vala
- src/config/GSettingsEngine.vala
- src/editing_tools/CropTool.vala
- src/publishing/PublishingUI.vala
Also removed `dataimports` schema as it wasn't used anywhere.
> Port last_xxxx settings to native GSettings

- src/config/Config.vala
> Config.vala: remove dead code

- src/config/Config.vala
This comment is no longer relevant to anything after removing a bunch of code from this file.
> Remove Config.vala comment

- src/FullScreenWindow.vala
- src/Page.vala
>  Use overlay for fullscreen toolbar instead of separate window 

- data/application.css
- src/FullScreenWindow.vala
> FullScreenWindow.vala: Use Gtk.Revealer to hide/show toolbar

- src/FullScreenWindow.vala
> Reveal toolbar on mouse motion

- src/Dimensions.vala
> Dimensions.vala: Crit instead of error on bad constraint; return original

- src/FullScreenWindow.vala
- src/Widgets/TransitionEffectSelector.vala
Removes enable/disable methods and use a property instead
> Create a property for auto dismiss toolbar

- plugins/pantheon-photos-publishing/PicasaPublishing.vala
- src/Checkerboard/CheckerboardPage.vala
- src/CollectionPage.vala
- src/CommandManager.vala
- src/CustomComponents.vala
- src/Dialogs/Dialogs.vala
- src/EditingHostPage.vala
- src/Photo.vala
- src/db/DatabaseTable.vala
- src/direct/DirectPhotoPage.vala
- src/photos/WebPSupport.vala
- src/plugins/ManifestWidget.vala
- src/sidebar/Branch.vala
Cleans up some trailing white-space and adds missing braces (particularly in Photo.vala)
> Cleanup code style

- src/Application.vala
> Always use dark theme

- src/editing_tools/AdjustTool.vala
* Use construct
* Don't nest grids
* Use properties
* Make (slightly more) sense
> Rewrite adjust dialog

- src/library/ImportQueuePage.vala
* organize
* Use var
* add instead of insert
> ImportQueuePage: cleanup toolbar

- src/Page.vala
Use construct, get rid of init_ui
> Page.vala: GObject style

- src/camera/ImportPage.vala
> Import Dialog: fix delete string

- src/camera/ImportPage.vala
None of these get methods are actually used outside this file :p
> ImportPage: Change several get methods to properties

- src/camera/ImportPage.vala
#323 
set_expand fixed this issue.
And also fixed the cropped image grid visible in the screenshot.
> Fixing: Import buttons aligned incorrectly

- src/events/EventsDirectoryPage.vala
> Fix month name format

- src/library/LibraryWindow.vala
> Don't switch focus if search entry has it

- src/AppWindow.vala
- src/util/DragAndDropHandler.vala
Looks like this is the only place this is used
> Move DND_ICON_SCALE to utils/dndhandler

- src/config/GSettingsEngine.vala
GLib has some built in stuff for verifying schema existence
> GSettingsEngine: replace deprecated GLib.Settings.list_schemas

- src/AppWindow.vala
- src/LibraryPhotoPage.vala
- src/PageWindow.vala
- src/direct/DirectPhotoPage.vala
> Use GLib.Action for Undo and Redo

- src/FullScreenWindow.vala
- src/Page.vala
- src/library/LibraryWindow.vala
- src/sidebar/Tree.vala
Based on https://gitlab.gnome.org/GNOME/shotwell/commit/eae3fa56c5e16447606e48dd587f55a976f2b922
> Deprecated gdk display device manager

- src/publishing/PublishingUI.vala
Also remove some weird size request stuff and remove the dialog close button.
> PublishingUI: Layout without alignments

- src/AppWindow.vala
- src/util/system.vala
> AppWindow: Remove unused methods

- src/MediaPage.vala
> MediaPage: Reduce method scope

- src/AppWindow.vala
- src/MediaPage.vala
- src/camera/ImportPage.vala
- src/events/EventsDirectoryPage.vala
- src/library/OfflinePage.vala
- src/library/TrashPage.vala
While we're in the ImportPage, DRY a little
> Use GLib.Action for Select All

- src/SinglePhotoPage.vala
Fix a crash introduced in #353 
Same as https://gitlab.gnome.org/GNOME/shotwell/commit/fe9bdea99da34fad44864ab9be0a2ae6fd3ab373
> Fix fullscreen crash

- src/AppWindow.vala
- src/CollectionPage.vala
- src/Commands.vala
- src/EditingHostPage.vala
- src/Event.vala
- src/LibraryPhotoPage.vala
- src/MediaPage.vala
- src/MediaViewTracker.vala
- src/SlideshowPage.vala
- src/Tag.vala
- src/camera/ImportPage.vala
- src/core/DataView.vala
- src/core/DataViewTypes.vala
- src/core/ViewCollection.vala
- src/events/EventPage.vala
- src/events/EventsDirectoryPage.vala
- src/library/LibraryWindow.vala
- src/sidebar/metadata/BasicProperties.vala
- src/sidebar/metadata/ExtendedProperties.vala
- src/sidebar/metadata/LibraryProperties.vala
- src/sidebar/metadata/MetadataSidebar.vala
- src/util/DragAndDropHandler.vala
And all the changes that come from moving `get_source ()` to the `source` property
> DataView: use gobject style construction

- src/core/AbstractViewManager.vala
- src/core/ViewCollection.vala
- src/meson.build
One class per file. Had to grep to find this before
> Move AbstractViewManager to its own file

- src/CollectionPage.vala
- src/CollectionViewManager.vala
- src/meson.build
> Move CollectionViewManager to its own file

- src/Page.vala
Remove a bunch of unused DnD code. The only piece here that seems to be used is `disable_drag_source ()`, but since `dnd_enabled` is always false, it just returns immediately.
Make one variable and one method private since they're only used here
> Page: remove dead code and reduce var scope

- src/Application.vala
- src/main.vala
Since Granite.Application is now officially deprecated
> Move from Granite.Application to Gtk.Application

- src/Dialogs/Dialogs.vala
> Dialogs.vala: Remove unused dialogs

- src/editing_tools/CropTool.vala
* Use GObject-style construction
* Reduce variable scope where possible
* Remove tooltips from label buttons
* Use Gtk.Button.from_icon_name
* Use SizeGroup instead of an extra box
* Use Gtk.Revealer instead of unpacking and packing widgets.
* Remove code related to hiding and showing the window, saving its size and position, etc. None of this is necessary since we just use a Revealer
* Use ":" instead of "x" since we're describing an aspect ratio not a size
> CropTool: Cleanups, use Revealer, GObject-style

- plugins/pantheon-photos-publishing-extras/RESTSupport.vala
- plugins/pantheon-photos-publishing-extras/YandexPublishing.vala
- plugins/pantheon-photos-publishing/FacebookPublishing.vala
- plugins/pantheon-photos-publishing/RESTSupport.vala
Fixes https://github.com/elementary/photos/issues/460 .
Fixed facebook's and yandex's too.
> fix scrolledwindow not expanding

- meson.build
- meson/post_install.py
> Add meson post install script

- src/Dialogs/Dialogs.vala
- src/Views/DirectPhotoPage.vala
> Use FileChooserNative

- src/Dialogs/Dialogs.vala
> Dialogs: save_import_results to FileChooserNative

- src/Dialogs/Dialogs.vala
> Dialogs: copy_files_dialog as Granite.MessageDialog

- src/main.vala
It's soooo tiny thing, but the case of "Of" is not consistent between these same sentences:
https://github.com/elementary/photos/blob/604b0a8c2691c9f69f94eacc900170549b931eb2/src/main.vala#L68
https://github.com/elementary/photos/blob/604b0a8c2691c9f69f94eacc900170549b931eb2/src/main.vala#L76
According to the [AP style](https://www.bkacontent.com/how-to-correctly-use-apa-style-title-case/), "of" is not capitalized.
> Fix the case of "Of"

- src/Dialogs/AdjustDateTimeDialog.vala
- src/Dialogs/Dialogs.vala
- src/Resources.vala
- src/Views/CollectionPage.vala
Dividing singular/plural by checking if a number is 1 or not does not work in some language.
> Use ngettext instead of checking if a number is 1 or not

- src/AppWindow.vala
- src/Application.vala
- src/BatchImport.vala
- src/MediaDataRepresentation.vala
- src/MetadataWriter.vala
- src/Upgrades.vala
- src/Views/DirectPhotoPage.vala
- src/Views/SlideshowPage.vala
- src/db/Db.vala
- src/main.vala
And replace Photos.Application.get_instance () with GLib.Application.get_default ()
> Application: Use Photos namespace

- src/Views/CollectionPage.vala
- src/Views/LibraryPhotoPage.vala
- src/photos/PhotoFileFormat.vala
> Show proper external apps

- src/Dialogs/ExportDialog.vala
> Improve export dialog UI

- data/io.elementary.photos.appdata.xml.in
- src/library/LibraryWindow.vala
> LibraryWindow: Show saved state correctly in the context-menu

- .github/workflows/main.yml
- io.elementary.photos.yml
> Add flatpak

- .github/workflows/main.yml
- README.md
- io.elementary.photos.yml
- meson.build
- src/AppWindow.vala
- src/PageWindow.vala
- src/direct/DirectWindow.vala
- src/library/LibraryWindow.vala
Let's go with the last one in the project! (https://github.com/orgs/elementary/projects/75)
Using Hdy.ApplicationWindow and Hdy.HeaderBar. I also added libhandy to the CI.
Fix https://github.com/elementary/photos/issues/581
@hanaral I guess it should also solve https://github.com/elementary/photos/issues/593?
> Fix #581: Use Hdy.ApplicationWindow and Hdy.HeaderBar

- src/Checkerboard/CheckerboardLayout.vala
- src/Views/CheckerboardPage.vala
- src/util/ui.vala
The same as `Gtk.Widget.move_focus ()`
> Checkerboard: Use Gtk.DirectionType

- src/Views/EditingHostPage.vala
- src/editing_tools/EditingToolWindow.vala
> EditingHostPage: don't track tool windows

- src/editing_tools/AdjustTool.vala
- src/editing_tools/CropTool.vala
- src/editing_tools/PhotoCanvas.vala
- src/editing_tools/RedEyeTool.vala
- src/editing_tools/StraightenTool.vala
* Replace getter methods with properties
* Remove unused methods
> PhotoCanvas: Use properties and remove unused

- src/Views/EditingHostPage.vala
Only a couple of lines, might as well just make it a lambda
> EditingHostPage: avoid getting library_window twice for sidebar button

- src/Dialogs/ExportDialog.vala
Might as well do some code style fixes while we're here
> Export Dialog: fix action area margin and cleanup

- .github/workflows/ci.yml
- io.elementary.photos.yml
* Only run CI on PRs
* Update flatpak build
* bump checkout to v2 for lint
* Use "daily" for platform version
> CI: Update Flatpak action

- src/VideoSupport.vala
- src/db/PhotoTable.vala
- src/util/file.vala
> Replace FileInfo.get_modification_time () in preparation for 2038

- plugins/pantheon-photos-publishing-extras/RESTSupport.vala
- plugins/pantheon-photos-publishing-extras/Resources.vala
- plugins/pantheon-photos-publishing-extras/shotwell-publishing-extras.vala
- plugins/pantheon-photos-publishing/FacebookPublishing.vala
- plugins/pantheon-photos-publishing/FlickrPublishing.vala
- plugins/pantheon-photos-publishing/PiwigoPublishing.vala
- plugins/pantheon-photos-publishing/Resources.vala
- plugins/pantheon-photos-transitions/Resources.vala
- src/main.vala
Replace all occurance of 'Shotwell' to 'Photos' where users can see.
> Replace all occurance of 'Shotwell' to 'Photos' in the UI

- src/editing_tools/StraightenTool.vala
For the last one that bases from EditingTool class. (yey!). Also fixed some code style conflicts
> Make StraightenTool Class gobject-style constructed

- src/editing_tools/EditingToolWindow.vala
Just simple code style fixes, before I proceed to PhotoCanvas.
> Some minor code style fixes

- src/editing_tools/PhotoCanvas.vala
GObject-construct PhotoCanvas.vala, the last one inside src/editing_tools. Also fixed some code style conflicts.
> GObject-construct PhotoCanvas

- data/io.elementary.photos.appdata.xml.in
- meson.build
> Release 2.7.5

- data/icons/128-viewer.svg
- data/icons/16-viewer.svg
- data/icons/24-viewer.svg
- data/icons/32-viewer.svg
- data/icons/48-viewer.svg
- data/icons/64-viewer.svg
- data/io.elementary.photos-viewer.desktop.in.in
- data/meson.build
Instead of relying on a non-fdo icon name for the viewer, ship our own icon.
Similar to previously, this icon differs from the main icon by using one photo instead of a stack of photos
> Add Photo Viewer icons

- .github/workflows/ci.yml
Also update the container we use to build the flatpak while we're here.
> Update flatpak actions to new namespace

- .github/workflows/ci.yml
- README.md
- io.elementary.photos.yml
- meson.build
- src/AppWindow.vala
- src/Views/CollectionPage.vala
- src/Views/DirectPhotoPage.vala
- src/Views/LibraryPhotoPage.vala
> Use Wallpaper Portal

- debian/control
> control: Require newer libglib2.0-dev and meson

- src/Resources.vala
- src/main.vala
- `_GITVERSION` is not defined anywhere
- `enum ShotwellCommand` is not used anywhere
- `do_system_pictures_import` is not set anywhere
- `debug_enabled` is not referenced anywhere
> main: Remove unused code
