elementary/photos

src/AppWindow.vala
* Properties over set methods
* Use `icon_name` instead of `set_icon_widget`
* Don't unnecessarily set a label that won't be shown
* Action entries on a single line each
=> AppWindow.vala: code style

data/application.css, data/io.elementary.photos.gresource.xml, src/CMakeLists.txt, src/CheckerboardLayout.vala
This moves application CSS from being embedded as a string in `CheckerBoardLayout` to a proper CSS file in a gresource
=> Move application CSS to a gresource

src/AppWindow.vala, src/CMakeLists.txt, src/FullScreenWindow.vala, src/PageWindow.vala
I fucked up my last merge. This fully breaks up this file into 3 files with correct names
This diff makes it looks like there are changes because of the file renaming, but there are no changes. I only split the classes into different files
=> Break up Window classes and name files correctly

src/MediaPage.vala, src/db/DatabaseTable.vala, src/sidebar/metadata/BasicProperties.vala
Been doing some debugging on photos recently and there's a few noisy warnings in the output.
* One was relating to an action called "Rate" which doesn't seem to exist anymore, so I've removed the remnant of that code that was causing the warning.
* The second was a `warning` every time the database was loaded. Changed that to an info log message instead.
* The last was a lot of failures with the reverse geocoding. The default for an unset lat and long was `-1` but it seemed the library used for fetching the lat and long from the photo was returning `0.0, 0.0` when the photo didn't have those tags set. `0.0, 0.0` is in the middle of the ocean below africa, so I don't think we'll have any photos taken there, and we're now avoiding running the geocoding code on all the photos without a …
=> Cleanup some warnings

src/Event.vala
Fixes #152 
There's a bunch of code in this method that would never execute, so remove it. Then the assertion that's causing the crash isn't needed anymore, so remove that too.
=> Fix crash when changing exposure time metadata

src/Page.vala
There were a bunch of fatals while in slideshow mode about trying to remove timeouts that couldn't be found.
Make sure we don't do that anymore.
=> Don't remove timeouts that don't exist anymore

src/CollectionPage.vala, src/PhotoPage.vala
Fixes #13 
Only show the "Open with RAW Editor" menu when it's sensitive (i.e. when you're acting on a RAW photo).
=> Hide insensitive RAW editor menu

src/PhotoPage.vala, src/library/LibraryWindow.vala
Fixes #153 
This looks like quite a large diff, but it's just moving a bunch of the toolbutton code out of the constructor of the PhotoPage into the get_toolbar method so that the toolbars can be recreated after they get destroyed when switching to a different page.
=> Ensure toolbars are correctly rebuilt when switching pages

.travis.yml, CMakeLists.txt, data/org.pantheon.photos-viewer.desktop.in.in, src/CMakeLists.txt, src/photos/PhotoFileFormat.vala, src/photos/WebPSupport.vala, vapi/libwebp.vapi
Fixes #108 
Adds read-only support for WebP encoded images. Images with and without alpha channels are supported. Test files can be found here:
https://developers.google.com/speed/webp/gallery
=> Support WebP image files

src/ThumbnailCache.vala
If a new file was added to the folder that photos was watching while it was running on a HiDPI display, it would crash due to the thumbnail generated not being the expected size.
This is a regression since adding the HiDPI thumbnail support and this resolves it.
=> Fix assertion crash on importing photos on HiDPI

src/PhotoPage.vala
I'm not entirely sure how/why this was working before, but all the widgets were getting added to `toolbar` when I'd written code that created and returned a `created_toolbar` object.
Either way, the code is less confusing now.
=> Fix mistake in #184

src/AppWindow.vala, src/Checkerboard/CheckerboardLayout.vala
Fixes #130 
Turns out we do include the `.checkerboard-layout` CSS in a GResource, it was just being loaded in `CheckerboardLayout.vala` which is only used in the library window and hence won't of worked in the direct photo viewer.
Move the GResource loading code out to a window class that is a parent of both sorts of windows.
=> Move CSS GResource loading to common class to both windows

src/library/LibraryWindow.vala
It seems the parent class constructor is causing some attempts to get the GSettings from the last commit earlier than the object is created. Move the creation of the GSettings object to be as early as possible in `construct`.
=> Move new GSettings init to construct

src/MediaPage.vala, src/config/ConfigurationInterfaces.vala, src/config/GSettingsEngine.vala, src/events/Branch.vala, src/events/EventPage.vala, src/events/EventsDirectoryPage.vala, src/library/Branch.vala, src/library/FlaggedPage.vala, src/library/LastImportPage.vala, src/library/LibraryWindow.vala, src/library/PhotosPage.vala, src/library/RawsPage.vala, src/library/VideosPage.vala, src/searches/SavedSearchPage.vala, src/tags/TagPage.vala
Also move the most commonly used versions of the `get_config_photos_sort` and `set_config_photos_sort` methods to a parent class instead of repeating it many times.
=>  Port sort order settings to native GSettings 

schemas/org.pantheon.photos.gschema.xml, src/CollectionPage.vala, src/Page.vala, src/Photo.vala, src/config/ConfigurationInterfaces.vala, src/config/GSettingsEngine.vala, src/events/EventsDirectoryPage.vala
I was porting these settings to native GSettings as I've been doing with the others. When it came to testing them, I noticed that they weren't really being used.
I think the original intention of these was that once you'd right clicked an image and said "Open With", it stored that application in GSettings. Then it looked like at some point in the past, it was possible to hold super and double click an image in your library and it would open in that "default" editor stored in GSettings.
That's been broken in master for who knows how long and seems like a bit of a hidden/confusing feature anyway. So I propose removing the GSettings and associated code altogether as per this branch.
=> Remove editing GSettings

src/Page.vala
These were used in the GSettings removed in the previous commit, but why were they ever a thing?!
=> Cleanup some unused structs

src/config/ConfigurationInterfaces.vala, src/config/GSettingsEngine.vala
This wasn't used anywhere as a contractor entry is used for setting desktop wallpapers from the context menu.
=> Remove background gnome settings code

src/PhotoPage.vala, src/direct/DirectPhotoPage.vala
There were quite a lot of errors in the console relating to the metadata sidebar when opening a photo directly in the viewer (i.e. via the file browser). This is because the sidebar is only available in the library mode and the cast to `LibraryWindow` was failing and producing a null pointer.
=> Prevent errors relating to the sidebar in direct photo viewer

src/PixbufCache.vala
This fixes the root cause of the crash in Vala 0.39.
For some reason the base constructor isn't setting those properties properly on the base class despite having the code there to do so. So do that in the child classes too.
=> Fix Vala 0.39 crash

data/application.css, src/FullScreenWindow.vala
As explained in Slack. The revealer was filling the screen and stealing mouse events from the canvas underneath.
Can test by zooming into a photo in fullscreen mode and attempting to pan by dragging with and without this branch.
Juno possibly seems unaffected.
=> Prevent revealer stealing mouse events

src/Dialogs/TextEntryDialog.vala, src/PageWindow.vala
Deprecated since 3.14 and doesn't do anything anymore since the whole window is a resize edge
=> Remove deprecated set_has_resize_grip

src/Checkerboard/CheckerboardItem.vala, src/MediaPage.vala
Seems we've been hit by what looks like a bug in the Vala compiler again where properties on sub-classes aren't set properly.
I'm going to try and write an easily reproducible piece of sample code but this should fix the issue for now with no negative side effects.
=> Fix initial blank collection in Juno

src/Page.vala, src/PhotoPage.vala
The boolean value `enable_interactive_zoom_refresh` was never set to true anywhere, so none of this code could be executed.
=> Remove un-used interactive zoom code

src/db/DatabaseTable.vala, src/db/PhotoTable.vala
Fixes #193 
The SQLite library was throwing assertions about trying to bind null pointers to strings in database queries.
Should be able to test this by running from the console and importing a new photo. The current master will probably spam the console with errors.
=> Don't bind null pointers to database queries

src/Checkerboard/CheckerboardItem.vala, src/MediaPage.vala, src/PixbufCache.vala
These were added in #247 and #241 to workaround the Vala compiler bug:
https://bugzilla.gnome.org/show_bug.cgi?id=791785
This bug has now been fixed and a new version of Vala has been released, so no longer affects photos.
=> Revert valac workarounds

src/EditingHostPage.vala
* Bump copyright
* Organize
* Use properties
* Remove `is_important` since this has to do with old Gtk.Toolbar icon vs text style stuff that isn't used anymore
* Don't set labels that will never be used
* Remove obvious comments
* Use a Gtk.Button instead of an eventbox for zoom default button
* Gtk.Grid instead of box
* Add tooltip to zoom default button (matches label in Code)
* Put separators between different types of actions
* Arrows on the left; fixes #276
=> EditingHostPage.vala: clean up toolbar

src/library/TrashPage.vala
* Bump copyright
* Organize
* Use var
* Add a separator between sidebar item and trash actions
* Get style etc from the base class toolbar instead of doing it again here
* Whitespace
* Remove an extra sep
* Remove obvious comments
=> TrashPage.vala: toolbar cleanups

src/camera/ImportPage.vala
* Bump copyright
* Organize
* Use properties
* Use `var`
* Fix underscores for translatable strings
* Remove obvious comments
=> ImportPage.vala: toolbar cleanup

src/direct/DirectWindow.vala
* Use Gtk.Grid instead of box
* Remove obvious comment
* Put all the headerbar stuff together in one spot
=> DirectWindow.vala: misc cleanup

src/Page.vala, src/library/LibraryWindow.vala
This is only used in one place and page_name is already public
=> Page: remove to_string

src/library/TopDisplay.vala
shorten long titles so they don't expand the window
fixes #278
=> Ellipsize long titles

src/searches/SavedSearchDialog.vala
Gtk.Alignment is deprecated. Use Grids and properties and all that fun stuff to replace it
While we're here, fix some spacing issues
=> SavedSearchDialog: Don't use alignment

src/events/EventsDirectoryPage.vala
There is a bug in master where toolbar items disappear after switching between nested event folders. This branch does not intend to fix that bug
=> EventsDirectoryPage: toolbar cleanup

src/sidebar/Tree.vala
Truncate long sidebar labels, fixes #263
=> Truncate long labels

src/direct/DirectPhotoPage.vala, src/direct/DirectWindow.vala
This affects the "Direct Viewer" or the previewer for when you open photos from Files
Afaict none of these tool items rely on the icon names, labels, or tooltips that were provided here. Except of course for the Save actions which are updated in this branch.
There are several action items for menus that don't exist anymore that are no longer used, so I removed those.
Please double check that all tool items match master in terms of icons and tooltips. AFAICT, all of the shortcuts are busted in master except save as. This branch doesn't fix that.
Next logical step after this branch seems to be to figure out why all the shortcuts are broken and then port these to GLib.Action :)
=> Slim down Gtk.Action usage in Direct Viewer

src/CollectionPage.vala
* Organize
* White space
* Get toolbar from base class instead of redoing it here
* We never show labels in toolbar so remove the label and `is_important`
* Separators are always hidden, so remove that too
=> CollectionPage: clean up toolbar

src/searches/SavedSearchDialog.vala
* Use grid as the gods intended instead of nesting
* Fix untranslatable string
* Add a tooltip
* Organize
=> SavedSearchDialog: Use fewer grids

src/AppWindow.vala, src/Resources.vala
Gets us a little closer to a world where we can use GLib.Action by not relying on Gtk.Action for setting button labels, icons, tooltips, etc
We still rely on sensitivity from the action because:
1. This is still supported in GLib.Action
2. This also controls the sensitivity of accelerators
=> AppWindow: Don't get undo/redo appearance from Gtk.Action

src/AppWindow.vala
Gtk.Action is deprecated, start the switch
=> AppWindow: use GLib.Action for Quit shortcut

src/sidebar/Tree.vala
There is no replacement for this, it's just removed
=> Tree.vala: Remove deprecated set_rules_hint

src/Widgets/SliderAssembly.vala
Replace these deprecated properties with their default values as defined here: https://developer.gnome.org/gtk2/stable/GtkSettings.html#GtkSettings--gtk-timeout-initial
=> SliderAssembly.vala: Replace deprecated gtk_timeout_foo

src/AppWindow.vala, src/Resources.vala, src/library/LibraryWindow.vala
Having the string in a constant is plenty abstracted for maintenance purposes. We don't need to abstract an obvious one-line method
=> Remove abstracted set_default_title method

src/Page.vala
For some reason I'm getting menus popping up at `0,0` on the display. Revert real quick until we can figure out a proper fix
=> Page.vala: Revert gtk.menu.popup change

src/AppWindow.vala, src/PageWindow.vala
This is going to be the basis for a lot of future GLib.Action branches. It turns out Gtk.ApplicationWindow has a built in actiongroup, so this makes it a lot easier for us to look up actions from other classes. Pretty neat
=> AppWindow: use built-in actiongroup

src/Dimensions.vala, src/EditingHostPage.vala, src/FullScreenWindow.vala, src/editing_tools/CropTool.vala
Based on:
* https://gitlab.gnome.org/GNOME/shotwell/commit/1b56db4b2bd9ee9ff35d2a91fcef7736f3431031
* https://gitlab.gnome.org/GNOME/shotwell/commit/b8309dd361b2fbfb284a30c31ffa87ad24d5f5f8
This branch can be rebase merged if that's desired
=> Replace deprecated gdk.screen

src/Dialogs/AdjustDateTimeDialog.vala
Fix a deprecation warning by using Gtk.Grid instead of nested boxes and Gtk.Alignment
This dialog is still a little wonky looking, but I'm just here to fix the warning
=> AdjustDateTimeDialog: Use Grids instead of Boxes and Alignments

data/shotwell.ui, src/Dialogs/Dialogs.vala, src/Dialogs/TextEntryDialog.vala
Rewrites the dialog with GObject-style construction (almost) and no UI files or Gtk.Builder or anything.
Solves a few deprecation warnings
=> TextEntryDialog: Rewrite without UI files

src/editing_tools/AdjustTool.vala, src/editing_tools/CropTool.vala, src/editing_tools/EditingTools.vala, src/editing_tools/RedEyeTool.vala, src/editing_tools/StraightenTool.vala
With GObject style and everything
=> EditingTools: rewrite EditingToolWindow as a Gtk.Dialog

src/AppWindow.vala, src/publishing/PublishingUI.vala
Uses Granite.MessageDialog instead of Gtk.MessageDialog
=> AppWindow.vala: Use Granite.MessageDialog for error dialog

src/AppWindow.vala, src/direct/DirectPhotoPage.vala
This is only used here and doesn't need to be abstracted
=> Move close without save dialog to DirectPhotoPage

src/AppWindow.vala, src/Dialogs/Dialogs.vala
* This is only used in Dialogs.vala so move from AppWindow.vala
* Use Granite.MessageDialog
* Use destructive action class
* Remove arguments that are always set to the same thing
=> Move negate_affirm_question to Dialogs and use Granite.MessageDialog

src/AppWindow.vala, src/Exporter.vala
This dialog is only used once, so just move it where it's used. Also use Granite.MessageDialog
=> Move negate_affirm_all_cancel_question to Exporter

src/AppWindow.vala, src/Dialogs/Dialogs.vala, src/SlideshowPage.vala, src/publishing/PublishingUI.vala
These aren't that different and can be combined with minimal effort. Using the app name as the primary text in a dialog is not useful.
=> AppWindow: combine error and error_with_title

src/AppWindow.vala, src/library/LibraryWindow.vala
* Use Granite.MessageDialog
* Parent is always `AppWindow.get_instance ()`, so we don't need to ask it as an arg
* Use built-in cancel
=> Clean up Cancel Affirm Question dialog

src/library/LibraryWindow.vala
I think this broke between gtk 3.18 and 3.22
=> LibraryWindow: remove an extra 1px border

src/Page.vala
Since we don't show labels in the toolbar, there's no need to set this label
=> Page: Don't set sidebar button label

src/MediaPage.vala, src/Resources.vala
`label` and `is_important` are not relevant here because we don't show toolbar button labels and the setting for changing button style in Gtk.Toolbar has been removed
=> MediaPage: Remove unused sidebar button properties

src/SlideshowPage.vala
Almost, because Photos throws some other error about `current`, so it needs some more work afterwards
=> SlideshowPage.vala: Use GObject-style construction

src/FullScreenWindow.vala
Bind properties instead of connecting to signals
=> FullScreenWindow: Bind auto dismiss to pin button

src/AppWindow.vala, src/library/LibraryWindow.vala
Fixes #436.
Moves setting up action groups to the constructor so that they get initialized before `LibraryWindow` wants to access them and moves menuitem labels to the action entries themselves.
=> Fix settings menu shortcuts and labels

src/AppWindow.vala, src/direct/DirectWindow.vala, src/library/LibraryWindow.vala
Fixes headerbar button order by packing buttons in the instance classes instead of the abstract class
=> Pack buttons in instance classes to fix order

src/library/LibraryWindow.vala
Not sure how this happened, but this fixes the searchbar so that it's in the right place in the headerbar
=> LibraryWindow: Fix searchbar placement

data/io.elementary.photos.appdata.xml.in
It looks like those remaning `<_li>` tags were left there by mistake. Changing them to `<li>` fixes appdata validation on fedora.
Fixes #459
=> appdata: replace remaining <_li> tags with plain <li>

README.md
The package is now tracked under "elementary-photos" instead of "pantheon-photos". This commit updates the badge to reflect this change.
=> README: update repology badge

src/photos/PhotoMetadata.vala
PR #498 accidentally dropped an unrelated line completely when wrapping the GExiv2 code inside a conditional. This PR re-introduces the missing line.
=> photos/PhotoMetadata: fix missing line accidentally dropped with PR #498

data/application.css, src/Checkerboard/CheckerboardLayout.vala
It looks like we were carrying some custom styles from when Photos was a light app, but we wanted the canvas behind images to be dark. Now that we're using the dark style, we can drop a lot. Plus, checkerboard and temperature scales are in the system stylesheet.
=> Drop styles that are already in system stylesheet

README.md
It is not required since a long time now
=> Remove python-scour

debian/control
=> Remove python-scour from the dependency list

src/Commands.vala, src/Views/ImportPage.vala, src/Widgets/TransitionEffectSelector.vala
Code still has a shed load of deprecation warnings and some invalid casts reported at run-time.
=> Fix unsafe cast warnings on compiling

src/Resources.vala
This is semantically incorrect, but it keeps the same icon in elementary icons while using an FD.o icon name. `accessories-camera` isn't a valid fd.o icon name and it will probably be removed
=> Resources: update RAW photo icon name

src/editing_tools/CropTool.vala
* Rename `ok_button` to `crop_button`
* Get rid of keypress handling that breaks keyboard navigation. Instead, set default
* Fix Crop and Cancel buttons being different size
* Code style
* get rid of single use method `set_normal_constraint_mode`
=> CropTool: Code style, minor fixes

src/FullScreenWindow.vala, src/Views/CollectionPage.vala, src/Views/EditingHostPage.vala, src/Views/EventsDirectoryPage.vala, src/Views/ImportPage.vala, src/Views/ImportQueuePage.vala, src/Views/LibraryPhotoPage.vala, src/Views/MediaPage.vala, src/Views/OfflinePage.vala, src/Views/Page.vala, src/Views/SlideshowPage.vala, src/Views/TagPage.vala, src/Views/TrashPage.vala, src/library/LibraryWindow.vala
Fixes #615 by replacing the future deprecated Gtk.Toolbar with Gtk.ActionBar
As ActionBar has no "insert at position" method some work will be required to maintain (approximately) the same appearance.
=> Substitute ActionBar for Toolbar

data/io.elementary.photos.appdata.xml.in
This is needed for appstream-generator to find the associated desktop file.
See also:
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
- https://github.com/ximion/appstream-generator/issues/88
=> Add launchable tag to appdata

meson.build, src/main.vala, vapi/config.vapi
Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)
=> l10n: Correctly setup the locales

src/Checkerboard/CheckerboardLayout.vala
I'm having some issues here with artifacting on the border. Maybe there's a clear method I'm unaware of? But this makes sure we use actual values for the rubberband element and no hardcoded values
=> CheckboardLayout: use rubberband widget path to draw selection band

src/direct/DirectWindow.vala
Automatically focus photo on file open. This prevents the **"Save as"** button from getting the initial focus which prevented the left and right arrows on the keyboard from navigating to the previous an next photos respectively.
Fixes #600
=> Automatically focus photo on file open

src/MediaMetadata.vala
This fixes date parsing enough to not segfault anymore for my own photo collection.
Fixes https://github.com/elementary/photos/issues/647
=> Fix invalid date segfault

src/Views/ImportPage.vala, src/camera/GPhoto.vala, src/photos/PhotoMetadata.vala, vapi/libexif.vapi, vapi/libgphoto2.vapi
Fixes #638 
Copied in the changes from the Shotwell vapi files and fixed up and tested the associated vala.
All of these code changes relate to importing and previewing files from a camera which I've just tested still works with my Pixel 4a.
I also changed how the `image-missing` icon is loaded in the import page as this was not working and causing criticals in the terminal.
This should get us some memory leak fixes as we've now got rid of a lot of the manual memory management that wasn't done right anyway.
=> Update vapi files

src/editing_tools/StraightenTool.vala
StraightenToolWindow has a base function which derives from EditingToolWindow, although the constructor of EditingToolWindow only sets transient_for property to the container, so transient_for can be called directly from StraightenToolWindow constructor itself without depending on the Parent Class (EditingToolWindow). The other functions included in the constructor are moved to the construct block to simplify further. Thanks @danrabbit
=> Simplify StraightenToolWindow class

src/Event.vala, src/VideoMetadata.vala
Fixes #628 
Fixes regression caused by incomplete conversion to DateTime from Time () in commit addac7152d803acc12231293200be64adfa8d1b8
Unfortunately any photos imported with the faulty version will have to be reimported or manually grouped into a single event for the day on which they were taken.
Another place was also found where Time () should have been replaced with DateTime () so that is also fixed.
=> Event.vala: Fix is_in_starting_day function. Use DateTime throughout

src/AppWindow.vala
We ship an RDNN icon for Photos these days, so we should use that here
=> AppWindow: Use shipped icon

plugins/pantheon-photos-publishing-extras/RESTSupport.vala, plugins/pantheon-photos-publishing-extras/YandexPublishing.vala, plugins/pantheon-photos-publishing/FacebookPublishing.vala, plugins/pantheon-photos-publishing/PicasaPublishing.vala, plugins/pantheon-photos-publishing/RESTSupport.vala, plugins/pantheon-photos-publishing/YouTubePublishing.vala
According to [this](https://github.com/WebKit/WebKit/blob/a8cdd64386ba4ac30479fdc25f5a9a2acc930813/Source/WebKit/UIProcess/API/glib/WebKitSettings.cpp#L1896) we can remove the deprecated `WebKit.settings.enable_plugins` instead of replacing it with another code
=> Plugins: Fix deprecations

src/AppWindow.vala, src/CommandManager.vala, src/Views/CollectionPage.vala, src/Views/EditingHostPage.vala
The Command class which is the parent class of the editing tools can be converted into gobject-style construction, which will also enable editing_tools to be gobject-style constructed.
=> Make Command Class Gobject-style Constructed

src/editing_tools/EditingTools.vala
The EditingTools class is the parent class of most editing tools that will also be revised to use gobject style construction, so it is good to do it here first. Also fixed some code style conflicts.
=> Make EditingTools a Gobject Class

src/editing_tools/AdjustTool.vala, src/editing_tools/CropTool.vala
Next to EditingTools, make children classes gobject style constructed. Starting with CropTools. Also fixed a simple block in AdjustTools.
=> Make CropTools Gobject-style constructed

src/editing_tools/RedEyeTool.vala
Make redeyetool gobject-style constructed. Also replaced specified type with `var` when there is clear indication of the instance.
=> Make RedeyeTool Class Gobject-style constructed

src/Views/EventsDirectoryPage.vala, src/Views/ImportPage.vala
* Stop critical terminal warning showing certain views
=> Lose unnecessary private copies of ui_settings

src/sidebar/metadata/BasicProperties.vala
* Stops critical warning when clicking on certain sidebar entries
=> Check for null and type before getting source properties

src/Views/CollectionPage.vala, src/Views/DirectPhotoPage.vala, src/Views/LibraryPhotoPage.vala
Extracted from #675 to reduce diff.
When running as a Flatpak the "Open with" submenus currently return no items but still appear as an empty menu.  This issue occurs on the Collection, Library and Direct pages. This PR fixes that.
This is effectively the same code repeated three times in different classes as virtually the same code appears 3 times in master.
DRYing is therefore possible but is left for a future PR (unless requested here).  Most of the extra lines are due to code style improvements.  The only change in logic is to return the number of items added to the submenu and set the sensitivity of the corresponding menu-item accordingly.
=> Fix empty Open with context submenus

src/Resources.vala
The icon name `office-calendar` doesn't exist in fd.o, but `x-office-calendar` does https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html
=> Resources: use fd.o icon name for calendar

po/extra/zh_HK.po
Right now we are not able to build Photos on Fedora 37:
https://github.com/meisenzahl/distro-agnostic/actions/runs/3987907130/jobs/6838343834#step:5:16634
This small change fixes this:
https://github.com/meisenzahl/distro-agnostic/actions/runs/3988175247/jobs/6838977411#step:5:18232
@ryonakano do you have any concerns changing the charset?
=> Fix translation charset

docs/meson.build
Motivated by https://github.com/elementary/mail/pull/917, I tried to build the docs here and found it fails as well :thinking: 
```
EditingToolWindow.vala:21.56-21.58: error: The symbol `Hdy' could not be found
AppWindow.vala:39.15-39.17: error: The symbol `Hdy' could not be found
PageWindow.vala:28.36-28.38: error: The symbol `Hdy' could not be found
```
=> docs: Declare libhandy-1 dependency

data/meson.build, data/viewer.desktop.in.in, po/extra/POTFILES
Desktops have to be prefixed with the app ID to be exported under flatpak, so we use a `.` not a `-` for the viewer desktop file
=> Fix viewer not being exported in Flatpak

data/io.elementary.photos.gschema.xml
Followup #761
This fixes the warning when compiling schemas:
```
user@VirtualBox-17958d80:~/work/switchboard-plug-locale$ LANG=C sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
Warning: undefined reference to <schema id='io.elementary.photos.sharing'/>
user@VirtualBox-17958d80:~/work/switchboard-plug-locale$ 
```
=> gschema: Remove alias to sharing

src/AppDirs.vala
`Resources.LIB` already has the `/usr` (or `/app` if Flatpak) prefix in meson.build so the previous code tries to search for `/usr/usr/lib/x86_64-linux-gnu` or `/app/app/lib` and causes the critical messages displayed on the terminal when launching and plugins not shown in the preferences dialog.
```
user@VirtualBox-17958d80:~/work/photos$ LANG=C io.elementary.photos 
** Message: 01:20:46.822: main.vala:347: Photos Photo Manager 8.0.0
(io.elementary.photos:67956): GLib-GIO-CRITICAL **: 01:20:46.835: g_file_get_child: assertion '!g_path_is_absolute (name)' failed
(io.elementary.photos:67956): GLib-GIO-CRITICAL **: 01:20:46.835: g_file_get_child: assertion 'G_IS_FILE (file)' failed
(io.elementary.photos:67956): GLib-GIO-CRITICAL **: 01:20:46.835: g_file_get_child: assertion 'G_IS_FILE …
```
=> AppDirs: Fix loading plugins

io.elementary.photos.json
It turns out we need a sandbox hole for home because the photos viewer can't open files outside the sandbox
=> Flatpak: add sandbox hole for home

data/meson.build, data/photos.desktop.in, data/viewer.desktop.in, po/extra/POTFILES
* Don't set exec name using build system
* Add `SingleMainWindow` key
* Remove unused `GenericName` key
=> Modernize desktop files, simplify build

src/MediaMetadata.vala
Fixes #641 
There was a coding error in the use of the `string.scanf` function in the fallback code - the `out` parameters were not correctly supplied.  
The same error was not made in the "normal" code path so it only occurs if an image has a non-standard/corrupt date-time tag.  Presumably this is rare.
The opportunity is taken to write both functions in `Vala` style rather than `C` style (i.e. using the `out` keyword).
=> MetadataDateTime: Fix crash in fallback scanf code

src/DirectoryMonitor.vala
There is no need to have a terminal warning about skipping hidden files - this is normal program behaviour.
=> DirectoryMonitor: Silence hidden file terminal warning

src/MediaMetadata.vala, src/photos/PhotoMetadata.vala
May fix some issues with loading corrupt metadata.
- Replaces an assert statement with throwing errors
- Replaces deprecated GExiv2 methods with new error throwing ones and handle errors where necessary
=> Make Photometadata class more robust

src/Views/SinglePhotoPage.vala
Fixes #789 
This fixes the issue on Wayland OS8.
=> Fix panning zoomed images on Wayland

data/icons/icons.gresource.xml, data/icons/view-pin-symbolic.svg
Symbolic icons need to have a path in Gtk4 to work correctly. While we're here, add missing non-fd.o `view-pin-symbolic`
=> Resource: add path to symbolics

meson.build, src/photos/PhotoMetadata.vala
Required for #809
- Add support for gexiv2-0.16
- It now adopts API versioning: https://gitlab.gnome.org/GNOME/gexiv2/-/releases/0.15.0
- Replace `GExiv2.Metadata.get_tag_description ()` which was deprecated in 0.12.2 and removed in gexiv2-0.16 with `GExiv2.Metadata.try_get_tag_description ()`
- Drop support for gexiv2 < 0.12.2
- Remove unused `GEXIV2_0_11` which was leftover from bc7feca8caa4c8fc076a759a2d36e26e93c75596
=> Add support for gexiv2-0.16

src/VideoSupport.vala
Fixes the following build warning:
```
../src/VideoSupport.vala:215.17-215.29: warning: `Gst.PbUtils.DiscovererInfo.get_tags' has been deprecated since 1.20
215 |             if (info.get_tags () != null && info.get_tags ().get_date_time (Gst.Tags.DATE, out video_date)) {
|                 ^~~~~~~~~~~~~                                                                                
../src/VideoSupport.vala:215.45-215.57: warning: `Gst.PbUtils.DiscovererInfo.get_tags' has been deprecated since 1.20
215 |             if (info.get_tags () != null && info.get_tags ().get_date_time (Gst.Tags.DATE, out video_date)) {
|                                             ^~~~~~~~~~~~~                                                    
```
The solution here is just what …
=> VideoSupport: Replace deprecated Gst.PbUtils.DiscovererInfo.get_tags

src/plugins/Plugins.vala
Fixes the following build warning:
```
../src/plugins/Plugins.vala:63.49-63.69: warning: `GLib.ModuleFlags.BIND_LAZY' has been deprecated since vala-0.46. Use LAZY
63 |         module = Module.open (file.get_path (), ModuleFlags.BIND_LAZY);
|                                                 ^~~~~~~~~~~~~~~~~~~~~  
../src/plugins/Plugins.vala:355.9-355.26: warning: `GLib.Module.SUFFIX' has been deprecated since 2.76
355 |     if (GLib.Module.SUFFIX in basename) {
|         ^~~~~~~~~~~~~~~~~~               
```
The solution for ModuleFlags.BIND_LAZY is to use the alternative method that [valadoc](https://valadoc.org/gmodule-2.0/GLib.ModuleFlags.BIND_LAZY.html) says.
Regarding to Module.SUFFIX, valadoc says nothing about alternative, but there are some hints in the original C source code: …
=> Plugins: Replace deprecated ModuleFlags.BIND_LAZY and Module.SUFFIX

README.md, meson.build
Use the feature of meson instead of handling fallback manually. From https://mesonbuild.com/Reference-manual_functions.html#dependency:
> Since 0.60.0 more than one name can be provided, they will be tried in order and the first name to be found will be used.
Also update README and meson.build to apply recent version limitation changes in #810 and #817
=> meson: Use multiple dependency name instead of manual fallback
